### PR TITLE
Don't fail the build when wasm modules are used.

### LINKED ISSUE #408: Build error when using a WebAssembly module
Webpack 4 supports modules written in WebAssembly. Here's a commit that adds such a module to the offline-plugin-pwa example:

https://github.com/mstange/offline-plugin-pwa/commit/a4b2fdf232bc2e1711a2c1c8c5639615fe4fe638

However, when using offline-plugin on a project with WebAssembly modules, the offline-plugin build fails:

```
$ npm run build

> pwa-conf-offline-plugin@1.0.0 build /Users/mstange/code/offline-plugin-pwa
> webpack --log-level=debug

ℹ ｢webpack｣: Starting Build
➤ ｢webpack｣: Input File System Purged
✖ ｢command｣: A webpack error occured while building: use --log-level=debug for more error detail
✖ ｢command｣: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
➤ ｢command｣: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type object
    at Hash.update (internal/crypto/hash.js:58:11)
    at Object.getHashDigest (/Users/mstange/code/offline-plugin-pwa/node_modules/offline-plugin/node_modules/loader-utils/index.js:248:7)
    at /Users/mstange/code/offline-plugin-pwa/node_modules/offline-plugin/lib/index.js:465:45
    at Array.forEach (<anonymous>)
    at OfflinePlugin.setHashesMap (/Users/mstange/code/offline-plugin-pwa/node_modules/offline-plugin/lib/index.js:460:39)
    at emitFn (/Users/mstange/code/offline-plugin-pwa/node_modules/offline-plugin/lib/index.js:276:18)
    at _err1 (eval at create (/Users/mstange/code/offline-plugin-pwa/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:17:1)
    at callback (/Users/mstange/code/offline-plugin-pwa/node_modules/copy-webpack-plugin/dist/index.js:77:17)
    at /Users/mstange/code/offline-plugin-pwa/node_modules/copy-webpack-plugin/dist/index.js:118:24
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwa-conf-offline-plugin@1.0.0 build: `webpack --log-level=debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwa-conf-offline-plugin@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mstange/.npm/_logs/2018-08-23T20_52_47_372Z-debug.log
```

You can reproduce this by checking out the [add-wasm branch in my offline-plugin-pwa fork](https://github.com/mstange/offline-plugin-pwa/tree/add-wasm) and running `npm install && npm run build`.

### PR DESCRIPTION
**Pull request by mstange**
Fixes #408.

The fix itself is straightforward but adding a test was a bit more troublesome. I had to upgrade eslint and add babel-eslint so that the dynamic `import()` syntax would pass eslint. I also tweaked the harness a bit to log more details when things fail. The test only has a reference for webpack4 and is skpped on earlier webpack versions.

### CODE REVIEW

**Comment by NekR** [comment]
Hey. Sorry for a delay. This is great that you did this. But `lib/` is generated folder. You need to modify files in `src/` and then generate `lib/` folder. See https://github.com/NekR/offline-plugin/blob/master/CONTRIBUTING.md for details.

**Comment by mstange** [comment]
The patch touches `src/` too. If I recall correctly, I generated the change to `lib/` the way you say (by building), but it's been a while and I don't 100% remember. I guess it's possible that I edited `lib/index.js` manually with the equivalent change. I can build again to make sure, if you'd like.

**Comment by mstange** [comment]
Thanks for taking a look!

**Comment by NekR** [comment]
Oh, yeah, indeed, there are changes in `src/` as well. My bad. I'll take a closer look at it soon 👌

**Comment by julienw** [comment]
hey @nekr, could you look at it ? :)

File: tests/legacy/config.js [hunk 1]
```diff
@@ -48,6 +56,7 @@ module.exports = function(OfflinePluginOptions, testFlags) {
 
   if (webpackMajorVersion === '4') {
```
Comment (GGAlanSmithee) [inline tests/legacy/config.js]: should probably use `if (parseInt(webpackMajorVersion, 10) >= 4)` to be future proof.

File: tests/legacy/config.js [hunk 2]
```diff
@@ -8,6 +8,14 @@ var compare = require('./compare');
 var webpackMajorVersion = require('webpack/package.json').version.split('.')[0];
 
 module.exports = function(OfflinePluginOptions, testFlags) {
+  testFlags = testFlags || {};
+
+  if (testFlags.minimumWebpackMajorVersion &&
+      parseInt(webpackMajorVersion, 10) < testFlags.minimumWebpackMajorVersion) {
+    throw new Error('unsupported webpack version');
+  }
+  delete testFlags.minimumWebpackMajorVersion;
```
Comment (GGAlanSmithee) [inline tests/legacy/config.js]: How come you are deleting this? If set, would you not expect it to be present further down the execution flow? Maybe I am missunderstanding something :)

File: lib/index.js [hunk 3]
```diff
@@ -462,7 +462,14 @@ var OfflinePlugin = (function () {
 
         if (typeof validatedPath !== 'string' || _this4.assets.indexOf(validatedPath) === -1) return;
 
-        var hash = _loaderUtils2['default'].getHashDigest(compilation.assets[key].source(), 'sha1');
+        var source = compilation.assets[key].source();
+        if (source instanceof ArrayBuffer) {
```
Comment (GGAlanSmithee) [inline lib/index.js]: Do you know of any other situation that could cause source to be an `ArrayBuffer`? (It shouldn't matter though, since the same logic should apply.)

**Comment by GGAlanSmithee** [comment]
@mstange I approved this with some minor comments, which you could look at. It would still require @NekR's approval before merge though

@NekR - the actual change in this PR is very minor and should not affect non-webassembly users, so I think it would be worth merging this. It's backwards compatible, so should fit in a patch / minor version

**Comment by NekR** [comment]
@GGAlanSmithee I think I can merge this.

**Comment by NekR** [comment]
Hmm, it fails CI after merge from master. Probably my or other PR changes did something to it.

**Comment by NekR** [comment]
Okay, it seems to be because of newer webpack version. I'll resolve that locally.

@mstange thanks for contributing this. It's very much appreciated. Great work 👍

@GGAlanSmithee thanks for taking care of this. It wouldn't be possible to merge and all this PRs right without you help 💪 👍
